### ISSUE TITLE
Question related to minitest-reporters

### ISSUE THREAD

**Issue by twnaing** [zidhuss/neotest-minitest#1]
If minitest-reporters is used, the output is not suitable for this adapter (except DefaultReporter)

If there is VIM env set, minitest-reporters does not use any reporters.

Can we set ENV via config or any other recommended way?

**Comment by zidhuss** [comment]
Hey thanks for reporting this (pun intended 😁)

I'm not able to reproduce this. I assumed the `VIM` variable is set automatically?

From the `$VIM` help:

>The environment variable "$VIM" is used to locate various user files for Nvim,
such as the user |config|.  This depends on the system, see
|startup|.
>
> Nvim will try to get the value for $VIM in this order:
>
>1. Environment variable $VIM, if it is set.
>2. Path derived from the 'helpfile' option, unless it contains some
   environment variable too (default is "$VIMRUNTIME/doc/help.txt").  File
   name ("help.txt", etc.) is removed.  Trailing directory names are removed,
   in this order: "doc", "runtime".
>3. Path derived from the location of the `nvim` executable.
>4. Compile-time defined installation directory (see output of ":version").
>After doing this once, Nvim sets the $VIM environment variable.

I tried reproducing with this example:

```ruby
# frozen_string_literal: true

require 'minitest/autorun'
require "minitest/reporters"

Minitest::Reporters.use! Minitest::Reporters::ProgressReporter.new

class ReportersTest < Minitest::Test
  def test_addition
    assert_equal 2, 1 + 1
  end
end
```

From within neovim no reporters were used. When I initiated the test in a separate terminal it was using the ProgressReporter.

**Comment by twnaing** [comment]
My bad. I think I have misconfigured something.
