### ISSUE TITLE
Tests in nested directories are not detected

### ISSUE THREAD

**Issue by mwagg** [zidhuss/neotest-minitest#13]
I work mostly in larger codebases where the tests directory is often nested a few levels deep i.e. `engines/some_engine/test/models/some_model_test.rb`. For these projects, this plugin does not detect those tests.

Looking into this, I noticed that the implementation of `filter_dir` filters out directories that are not at the root or have "test" in their name. That causes the nested tests to be ignored (in my example the directory `engines/some_engine` returns false from `filter_dir` and so no file deeper than that is examined).

As I understand it, `filter_dir` is supposed to filter out directories that  should not be searched for tests, and so I'm not sure if the current implementation is correct. If I look at other plugins (for example [neotest-vitest](https://github.com/marilari88/neotest-vitest/blob/c0ea475596483eb02fa8e92c6be65c0536d55630/lua/neotest-vitest/init.lua#L71) or [neotest-python](https://github.com/nvim-neotest/neotest-python/blob/2e83d2bc00acbcc1fd529dbf0a0e677cabfe6b50/lua/neotest-python/init.lua#L84)), they simply check if the directory is one of the well known ones for each language that will contain dependencies (and so tests that are not strictly part of the project). 

I have a fork of this plugin and updated the [implementation there](https://github.com/mwagg/neotest-minitest/blob/04e2eb306ca2f564bc85200b5c464ca313b899d9/lua/neotest-minitest/init.lua#L32) to what I think it should be and the plugin now behaves as I expected and I'm not seeing any negative performance as a result.

I just wanted to sense check I'm not missing something here. I'm happy to send a PR for this if my thinking is correct.

**Comment by zidhuss** [comment]
Your understanding makes sense to me. I'd be happy to accept a PR with your implementation.

**Comment by mwagg** [comment]
@zidhuss sorry this took me a while to get to, but I just sent a PR for it https://github.com/zidhuss/neotest-minitest/pull/15
