### ISSUE TITLE
Support for debugging tests

### ISSUE THREAD

**Issue by gingermusketeer** [zidhuss/neotest-minitest#25]
Hi,

I have been trying this package out and tried to debug a failing test with https://github.com/mfussenegger/nvim-dap. Looking at the [neotest documentation](https://github.com/nvim-neotest/neotest?tab=readme-ov-file#strategies) there needs to be support for the dap test strategy in this package. From what I can tell this is not implemented.

Would you be keen to support this strategy?

**Comment by stephenprater** [comment]
@gingermusketeer #31  - take a look.
