### ISSUE TITLE
Unable to get neotest to run tests for a minitest file

### ISSUE THREAD

**Issue by exosyphon** [zidhuss/neotest-minitest#3]
When I run `lua require('neotest').run.run(vim.fn.expand('%'))` I get "No tests found". But if I run `:!ruby %` then the tests run and provide output. 

Any help in figuring out what I am missing would be great.

**Comment by zidhuss** [comment]
Hey @exosyphon could you share the file you're trying to run the tests on? Maybe the treesitter query that detects tests isn't detecting the tests.

**Comment by exosyphon** [comment]
Sure thing! This is an example from https://exercism.org/tracks/ruby/exercises/two-fer 

```ruby
require 'minitest/autorun'
require_relative 'two_fer'

# Common test data version: 1.1.0 c080bdf
class TwoFerTest < Minitest::Test
  def test_no_name_given
    assert_equal 'One for you, one for me.', TwoFer.two_fer
  end

  def test_a_name_given
    skip
    assert_equal 'One for Alice, one for me.', TwoFer.two_fer('Alice')
  end

  def test_another_name_given
    skip
    assert_equal 'One for Bob, one for me.', TwoFer.two_fer('Bob')
  end
end
```

**Comment by zidhuss** [comment]
Does the file name end in `_test.rb`? I tried to reproduce with the example you gave and I'm only getting the behaviour you described when the file name doesn't end in `_test.rb`.

This adapter only recognizes test files that end in `_test.rb`. See https://github.com/zidhuss/neotest-minitest/blob/25dbe6e56a245899661f025a957b6e2502900a0d/lua/neotest-minitest/init.lua#L18-L23

**Comment by exosyphon** [comment]
The test file does end with _test.rb but it is at the same level as the implementation. Not sure if that matters. Here is the directory structure:

- README.md
- two_fer.rb
- two_fer_test.rb

**Comment by zidhuss** [comment]
The default test command assumes a `Gemfile` because it runs `bundle exec ruby -Itest`.

The b3fde2c commit made the test command configurable. To get your example to work you can modify your default test command:

```lua
require("neotest-minitest")({
    test_cmd = function()
        return vim.tbl_flatten({
            "ruby",
            "-Itest",
        })
    end,
}),
```

**Comment by exosyphon** [comment]
I still couldn't get this to work for me. I ended up just generating a Gemfile and that got the tests to run.
