### ISSUE TITLE
Error when using on mini test file

### ISSUE THREAD

**Issue by serversidepiece** [zidhuss/neotest-minitest#4]
Getting this error when running this on a test file, the test runs in the output console when attaching and successfully completes but then this error displayed below...

```
neotest-minitest: ...are/nvim/site/pack/packer/start/neotest/lua/nio/init.lua:105: The coroutine failed with this message:
...ker/start/neotest-minitest/lua/neotest-minitest/init.lua:142: table index is nil
stack traceback:
        ...ker/start/neotest-minitest/lua/neotest-minitest/init.lua: in function '_parse_test_output'
        ...ker/start/neotest-minitest/lua/neotest-minitest/init.lua:177: in function 'results'
        .../pack/packer/start/neotest/lua/neotest/client/runner.lua:131: in function '_run_spec'
        .../pack/packer/start/neotest/lua/neotest/client/runner.lua:89: in function <.../pack/packer/start/neotest/lua/neotest/client/runner.lua:88>
```

**Comment by zidhuss** [comment]
It looks like the plugin isn't parsing the test output correctly. Can you share the output/results of the test run?

**Comment by lgeralds** [comment]
I recognize this error and just started looking for a fix. The mailer tests were crashing. And so were channel tests. And connection tests.

This is what I've discovered: neotest-minitest/init.lua#line 61 is missing superclasses

 (superclass (scope_resolution) @superclass (#match? @superclass "(ActionDispatch::IntegrationTest|ActiveSupport::TestCase|ActionMailer::TestCase|ActionCable::Channel::TestCase|ActionCable::Connection::TestCase)$"))

This fixes the tests mentioned above.

I'm trying to solve the problems with the system tests. Adding ActionDispatch::SystemTestCase and/or ApplicationSystemTestCase to the above line doesn't help.

I'm thinking it has something to do with how the tests are launched at the command line.

**Comment by johnpitchko** [comment]
Howdy, I'm new to using Neotest and am running into this issue now when testing ActiveJob. What can I provide to help with debugging?

**Comment by zidhuss** [comment]
Hey @johnpitchko, thanks for reporting.

To help with debugging it would be helpful if you could share the output of your tests and any specific error messages you've encountered.

It would also help to know how you'd usually launch your tests?
